services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file:
      # - .env.dev
      - .env.dev.docker
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    restart: always
    env_file:
      - .env.dev.docker
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  seed:
    build: .
    # command: ["node", "seeders/data.js"]
    command:
      [
        "bash",
        "-c",
        "./wait-for-it.sh mongo:27017 -- echo 'MongoDB is ready, running seed...' && node seeders/data.js",
      ]
    env_file:
      - .env.dev.docker
    depends_on:
      - mongo

volumes:
  mongo-data:
  redis-data:
